((nil . ((projectile-project-compilation-cmd . "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build;cmake --build build")
	 (compile-command . "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build;cmake --build build")
         (projectile-project-run-cmd . "LD_LIBRARY_PATH=mir/build/lib/ MIR_SERVER_PLATFORM_PATH=mir/build/lib/server-modules/ ./build/X13 --enable-x11=true --platform-display-libs=mir:x11 --platform-rendering-libs=mir:egl-generic --debug")
	 )
      )
 )
